incidencias_backend_list_incidencia:
    pattern:  /
    defaults: { _controller: BackendBundle:Incidencia:portada }

incidencias_backend_edit_incidencia:
    pattern:  /incidencia/{id}
    defaults: { _controller: BackendBundle:Incidencia:getUpdate }
    
incidencias_backend_save_incidencia:
    pattern:  /incidencia/{id}/save
    defaults: { _controller: BackendBundle:Incidencia:update }
    
incidencias_show_image:
    pattern:  /image/{id}
    defaults: { _controller: BackendBundle:Incidencia:showImage }
    
    
    
incidencias_backend_list_empleado:
    pattern:  /empleado
    defaults: { _controller: BackendBundle:Empleado:portada }
    

incidencias_backend_create_empleado:
    pattern:  /empleado/create
    defaults: { _controller: BackendBundle:Empleado:getCreate }

incidencias_backend_edit_empleado:
    pattern:  /empleado/{id}/edit
    defaults: { _controller: BackendBundle:Empleado:getUpdate }
incidencias_backend_delete_empleado:
    pattern:  /empleado/{id}/delete
    defaults: { _controller: BackendBundle:Empleado:delete }
    
incidencias_backend_save_empleado:
    pattern:  /empleado/save/{id}
    defaults: { _controller: BackendBundle:Empleado:update ,id:-1}
    
    