incidencias_incidencia_homepage:
    pattern:  /
    defaults: { _controller: IncidenciaBundle:Default:index }
incidencias_incidencia_response:
    pattern:  /enviar
    defaults: { _controller: IncidenciaBundle:Default:enviarIncidencia }
incidencias_database_init:
    pattern:  /reiniciarBaseDeDatos
    defaults: { _controller: IncidenciaBundle:Default:initDatabase }
