parameters:
#    incidencias_incidencia.example.class: Incidencias\IncidenciaBundle\Example

services:
#    incidencias_incidencia.example:
#        class: %incidencias_incidencia.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
